[package]
name = "DesignPatternRust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "AbstractFactoryStatic"
path = "AbstractFactory/src/app/main.rs"

[[bin]]
name = "AbstractFactoryDynamic"
path = "AbstractFactory/src/app-dyn/main.rs"